dev@dev-vm:~/Downloads/lab_etl/data_for_labs/lab_airflow/workshop-on-ETL/practice/business_case_rocket_26$ docker compose down -v
[+] down 8/8
 ✔ Container airflow-scheduler                  Removed                                                       0.0s
 ✔ Container jupyter-ml                         Removed                                                       0.0s
 ✔ Container streamlit-app                      Removed                                                       0.0s
 ✔ Container airflow-webserver                  Removed                                                       0.0s
 ✔ Container airflow-init                       Removed                                                       0.0s
 ✔ Container postgres-airflow                   Removed                                                       0.3s
 ✔ Volume business_case_rocket_26_postgres_data Removed                                                       0.1s
 ✔ Network business_case_rocket_26_etl-network  Removed                                                       0.1s
dev@dev-vm:~/Downloads/lab_etl/data_for_labs/lab_airflow/workshop-on-ETL/practice/business_case_rocket_26$ docker compose up -d
[+] up 8/8
 ✔ Network business_case_rocket_26_etl-network  Created                                                      0.1ss
 ✔ Volume business_case_rocket_26_postgres_data Created                                                      0.0ss
 ✔ Container postgres-airflow                   Healthy                                                      7.3ss
 ✔ Container jupyter-ml                         Created                                                      0.1ss
 ✔ Container streamlit-app                      Created                                                      0.1ss
 ✘ Container airflow-init                       Error service "airflow-init" didn't complete successful...   50.8s
 ✔ Container airflow-scheduler                  Created                                                      0.1ss
 ✔ Container airflow-webserver                  Created                                                      0.1ss
service "airflow-init" didn't complete successfully: exit 2
dev@dev-vm:~/Downloads/lab_etl/data_for_labs/lab_airflow/workshop-on-ETL/practice/business_case_rocket_26$ docker compose logs airflow-init --tail=30
airflow-init  | 
airflow-init  | Create a user
airflow-init  | 
airflow-init  | Options:
airflow-init  |   -h, --help            show this help message and exit
airflow-init  |   -e, --email EMAIL     Email of the user
airflow-init  |   -f, --firstname FIRSTNAME
airflow-init  |                         First name of the user
airflow-init  |   -l, --lastname LASTNAME
airflow-init  |                         Last name of the user
airflow-init  |   -p, --password PASSWORD
airflow-init  |                         Password of the user, required to create a user without --use-random-password
airflow-init  |   -r, --role ROLE       Role of the user. Existing roles include Admin, User, Op, Viewer, and Public
airflow-init  |   --use-random-password
airflow-init  |                         Do not prompt for password. Use random string instead. Required to create a user without --password
airflow-init  |   -u, --username USERNAME
airflow-init  |                         Username of the user
airflow-init  |   -v, --verbose         Make logging output more verbose
airflow-init  | 
airflow-init  | examples:
airflow-init  | To create an user with "Admin" role and username equals to "admin", run:
airflow-init  | 
airflow-init  |     $ airflow users create \
airflow-init  |           --username admin \
airflow-init  |           --firstname FIRST_NAME \
airflow-init  |           --lastname LAST_NAME \
airflow-init  |           --role Admin \
airflow-init  |           --email admin@example.org
airflow-init  | 
airflow-init  | airflow users create command error: the following arguments are required: -e/--email, -f/--firstname, -l/--lastname, -r/--role, -u/--username, see help above.
dev@dev-vm:~/Downloads/lab_etl/data_for_labs/lab_airflow/workshop-on-ETL/practice/business_case_rocket_26$ B

services:
  postgres:
    image: postgres:13
    container_name: postgres-airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - etl-network

  airflow-init:
    image: custom-airflow:slim-2.8.1-python3.11
    container_name: airflow-init
    entrypoint: /bin/bash               # ← переопределяем точку входа
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    command: >
      -c "
        set -e
        echo 'Waiting for postgres...'
        until pg_isready -h postgres -U airflow; do sleep 2; done
        echo 'Initializing Airflow DB...'
        airflow db init
        echo 'Creating admin user if not exists...'
        airflow users list | grep -q admin || \
          airflow users create \
            --username admin \
            --password admin \
            --firstname Admin \
            --lastname User \
            --role Admin \
            --email admin@example.com
        echo 'Airflow init completed successfully.'
      "
    networks:
      - etl-network

  airflow-webserver:
    image: custom-airflow:slim-2.8.1-python3.11
    container_name: airflow-webserver
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: dummy
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: webserver
    networks:
      - etl-network

  airflow-scheduler:
    image: custom-airflow:slim-2.8.1-python3.11
    container_name: airflow-scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    command: scheduler
    networks:
      - etl-network

  jupyter:
    image: custom-airflow:slim-2.8.1-python3.11
    container_name: jupyter-ml
    user: "50000:0"
    working_dir: /opt/airflow
    volumes:
      - .:/opt/airflow
    ports:
      - "8888:8888"
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password='' --notebook-dir=/opt/airflow
    networks:
      - etl-network

  streamlit:
    image: custom-airflow:slim-2.8.1-python3.11
    container_name: streamlit-app
    user: "50000:0"
    working_dir: /opt/airflow
    volumes:
      - ./app:/opt/airflow/app
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    ports:
      - "8501:8501"
    command: streamlit run app/app.py --server.address=0.0.0.0 --server.port=8501 --server.headless=true
    networks:
      - etl-network

networks:
  etl-network:
    driver: bridge

volumes:
  postgres_data:
